### ISSUE TITLE
License

### ISSUE THREAD

**Issue by epiloque** [occam-proof-assistant/Pearce-Kelly#2]
Hello,

Is this code open source?

Thank you!

**Comment by djalbat** [comment]
Absolutely. Go right ahead and use it. I'm sorry that there is currently no license.

**Comment by epiloque** [comment]
@jecs-imperial @djalbat can you please add a `LICENSE` file. Thank you!

**Comment by jecs-imperial** [comment]
Sure. I will get around to adding licenses to all my open source projects soon. I'll re-open the issue and only close it when I have done so.

The emphasis was unnecessary, by the way.
